#include"main.h"

//*******************************************************************************************************************************************
//                                          Урок 8. Механизм исключительных ситуаций в С++
//
//  Написать функцию div, которая должна вычислять результат деления двух целых чисел и запускать исключение DivisionByZero, если делитель равен 0.
//  В функции main ввести два целых числа и вывести их неполное частное, если делитель не равен нулю, и сообщение об ошибке, если равен.
//
//*******************************************************************************************************************************************

using namespace std;
template<typename  T>
T div(T val, T divider){
	if (divider == 0)
	{
		throw "Ошибка - на 0 делить нельзя!!!!"; 
	}
	return val / divider;
}
//*******************************************************************************************************************************************
int main() {
	setlocale(LC_ALL, "rus");
	double val; 
	double divider;
	while (true) {
		char strQ;
		cout << "Введите первое число : ";
		cin >> val;
		cout << "Введите второе число : ";
		cin >> divider;
		try
		{
			cout << "Результат деления: " << val << " / " << divider << " = " << div(val, divider) << endl;
		}
		catch (char* str)
		{
			cout << str << endl;
		}
		cout << endl;

		cin.ignore();
		cout << "Произвести еще вычисления ? (Y / N)  " ;
		strQ = getchar();
		if (strQ != 'Y' && strQ != 'y') break;
		cout << endl;
	}
	cout << endl;
	system("pause");
	return 0;
}
